### ISSUE TITLE
community health files

### ISSUE THREAD

**Issue by duncdrum** [BetaMasaheft/.github#1]
see https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file 

with forms for issue templates these can be pretty elaborate. But its something the project needs to decide upon.

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Documentation/blob/c567c510dbcca64bbd09d4c230f3c1d2c0aeaf61/CONTRIBUTING.md
https://github.com/BetaMasaheft/Documentation/blob/c567c510dbcca64bbd09d4c230f3c1d2c0aeaf61/CODE_OF_CONDUCT.md

we used to have issue templates but in an email discussion (3 Feb 2022) decided against them and removed them
