### ISSUE TITLE
set-output deprecation warning for github action

### ISSUE THREAD

**Issue by duncdrum** [BetaMasaheft/.github#3]
@line-o affects all data repos

see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ 

all instances of 
```
echo "::set-output name={name}::{value}"
```

should become

```
echo "{name}={value}" >> $GITHUB_OUTPUT
```

https://github.com/BetaMasaheft/.github/blob/f2be958de1c2d55f85057197daadebbeb027c114/workflow-templates/validate_pr.yml#L33

**Comment by line-o** [comment]
It will first be deprecated and then at some point no longer be possible. Good to know that in advance, thanks @duncdrum so we are prepared.
